name: Deploy to Azure App Service

# Manually trigger deployment when ready
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Create deployment package
      run: |
        pip install --target .python_packages/lib/site-packages -r api/requirements.txt
        zip -r deploy.zip . -x "*.git*" "tests/*" "*.md" ".venv/*" "__pycache__/*"
    
    # To enable automatic deployment:
    # 1. Get publish profile from Azure Portal
    # 2. Add it as AZURE_WEBAPP_PUBLISH_PROFILE secret in GitHub
    # 3. Uncomment the deploy step below
    
    # - name: Deploy to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'photo-log-map-api'
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #     package: deploy.zip